[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
tokenized_vaults_program = "YyUUJsRpeJ5fJEL6JBD7LKibaK43LXov4FzHs2w53J4"

[programs.localnet]
tokenized_vaults_program = "YyUUJsRpeJ5fJEL6JBD7LKibaK43LXov4FzHs2w53J4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
